export const WORKOUT_PLANS = [
  // Strength Plans
  {
    id: 'wp1',
    name: 'Shadow Strength — Upper Body',
    category: 'strength',
    rank: 'E',
    duration: 30,
    description: 'Build foundational upper body power through the Shadow Monarch\'s core regimen.',
    exercises: [
      { name: 'Push-ups', sets: 3, reps: 20, unit: 'reps', rest: 60, type: 'strength' },
      { name: 'Diamond Push-ups', sets: 3, reps: 15, unit: 'reps', rest: 60, type: 'strength' },
      { name: 'Pike Push-ups', sets: 3, reps: 12, unit: 'reps', rest: 60, type: 'strength' },
      { name: 'Tricep Dips', sets: 3, reps: 15, unit: 'reps', rest: 60, type: 'strength' },
      { name: 'Plank', sets: 3, reps: 30, unit: 'seconds', rest: 45, type: 'endurance' },
    ],
  },
  {
    id: 'wp2',
    name: 'Shadow Strength — Lower Body',
    category: 'strength',
    rank: 'E',
    duration: 35,
    description: 'Forge legs of iron through Jin-Woo\'s foundational lower body protocol.',
    exercises: [
      { name: 'Bodyweight Squats', sets: 4, reps: 30, unit: 'reps', rest: 60, type: 'strength' },
      { name: 'Lunges', sets: 3, reps: 20, unit: 'reps', rest: 60, type: 'strength' },
      { name: 'Glute Bridges', sets: 3, reps: 25, unit: 'reps', rest: 45, type: 'strength' },
      { name: 'Calf Raises', sets: 4, reps: 40, unit: 'reps', rest: 30, type: 'strength' },
      { name: 'Jump Squats', sets: 3, reps: 15, unit: 'reps', rest: 90, type: 'cardio' },
    ],
  },
  {
    id: 'wp3',
    name: 'Monarch\'s Power — Full Body',
    category: 'strength',
    rank: 'D',
    duration: 45,
    description: 'A complete full-body circuit designed for D-rank hunters pushing toward C.',
    exercises: [
      { name: 'Pull-ups', sets: 4, reps: 10, unit: 'reps', rest: 90, type: 'strength' },
      { name: 'Push-ups', sets: 4, reps: 25, unit: 'reps', rest: 60, type: 'strength' },
      { name: 'Squats', sets: 4, reps: 30, unit: 'reps', rest: 60, type: 'strength' },
      { name: 'Dips', sets: 3, reps: 20, unit: 'reps', rest: 60, type: 'strength' },
      { name: 'Burpees', sets: 3, reps: 15, unit: 'reps', rest: 90, type: 'cardio' },
      { name: 'Plank', sets: 3, reps: 60, unit: 'seconds', rest: 45, type: 'endurance' },
    ],
  },
  {
    id: 'wp4',
    name: 'Shadow Sovereign — Elite Strength',
    category: 'strength',
    rank: 'S',
    duration: 70,
    description: 'The ultimate strength protocol. For S-rank hunters only.',
    exercises: [
      { name: 'Muscle-ups', sets: 5, reps: 8, unit: 'reps', rest: 120, type: 'strength' },
      { name: 'One-arm Push-up Practice', sets: 4, reps: 10, unit: 'reps', rest: 120, type: 'strength' },
      { name: 'Pistol Squats', sets: 4, reps: 10, unit: 'reps', rest: 90, type: 'strength' },
      { name: 'Handstand Push-ups', sets: 3, reps: 8, unit: 'reps', rest: 120, type: 'strength' },
      { name: 'L-sit Hold', sets: 3, reps: 20, unit: 'seconds', rest: 60, type: 'endurance' },
      { name: 'Explosive Burpees', sets: 4, reps: 20, unit: 'reps', rest: 90, type: 'cardio' },
    ],
  },
  // Cardio Plans
  {
    id: 'wp5',
    name: 'Agility Protocol — Sprint Training',
    category: 'cardio',
    rank: 'D',
    duration: 40,
    description: 'Build explosive speed and agility through interval sprint work.',
    exercises: [
      { name: 'Warm-up Jog', sets: 1, reps: 5, unit: 'minutes', rest: 0, type: 'cardio' },
      { name: '100m Sprint', sets: 8, reps: 1, unit: 'effort', rest: 90, type: 'cardio' },
      { name: 'High Knees', sets: 4, reps: 30, unit: 'seconds', rest: 30, type: 'cardio' },
      { name: 'Lateral Shuffles', sets: 4, reps: 30, unit: 'seconds', rest: 30, type: 'cardio' },
      { name: 'Cool-down Walk', sets: 1, reps: 5, unit: 'minutes', rest: 0, type: 'cardio' },
    ],
  },
  {
    id: 'wp6',
    name: 'Shadow March — Distance Run',
    category: 'cardio',
    rank: 'C',
    duration: 60,
    description: 'Test your endurance with a sustained long-distance run.',
    exercises: [
      { name: 'Warm-up Stretch', sets: 1, reps: 5, unit: 'minutes', rest: 0, type: 'flexibility' },
      { name: 'Steady-state Run', sets: 1, reps: 45, unit: 'minutes', rest: 0, type: 'cardio' },
      { name: 'Cool-down Walk', sets: 1, reps: 5, unit: 'minutes', rest: 0, type: 'cardio' },
      { name: 'Calf Stretches', sets: 1, reps: 5, unit: 'minutes', rest: 0, type: 'flexibility' },
    ],
  },
  // Endurance
  {
    id: 'wp7',
    name: 'Iron Wall — Core Endurance',
    category: 'endurance',
    rank: 'D',
    duration: 35,
    description: 'Forge a core of absolute endurance with high-volume bodyweight work.',
    exercises: [
      { name: 'Sit-ups', sets: 5, reps: 40, unit: 'reps', rest: 30, type: 'endurance' },
      { name: 'Leg Raises', sets: 5, reps: 25, unit: 'reps', rest: 30, type: 'endurance' },
      { name: 'Bicycle Crunches', sets: 4, reps: 30, unit: 'reps', rest: 30, type: 'endurance' },
      { name: 'Plank', sets: 4, reps: 60, unit: 'seconds', rest: 45, type: 'endurance' },
      { name: 'Side Plank', sets: 3, reps: 45, unit: 'seconds', rest: 30, type: 'endurance' },
      { name: 'Mountain Climbers', sets: 3, reps: 40, unit: 'reps', rest: 45, type: 'cardio' },
    ],
  },
  // Flexibility
  {
    id: 'wp8',
    name: 'Shadow Flow — Mobility',
    category: 'flexibility',
    rank: 'E',
    duration: 25,
    description: 'Maintain peak movement quality through focused mobility work.',
    exercises: [
      { name: 'Dynamic Warm-up', sets: 1, reps: 5, unit: 'minutes', rest: 0, type: 'flexibility' },
      { name: 'Hip Flexor Stretch', sets: 3, reps: 60, unit: 'seconds', rest: 15, type: 'flexibility' },
      { name: 'Hamstring Stretch', sets: 3, reps: 45, unit: 'seconds', rest: 15, type: 'flexibility' },
      { name: 'Shoulder Circles', sets: 2, reps: 20, unit: 'reps', rest: 15, type: 'flexibility' },
      { name: 'Spinal Rotation', sets: 3, reps: 30, unit: 'seconds', rest: 15, type: 'flexibility' },
      { name: 'Child\'s Pose', sets: 2, reps: 60, unit: 'seconds', rest: 0, type: 'flexibility' },
    ],
  },
  // 7-Day Hypertrophy Program
  {
    id: 'hw1',
    name: 'Push A — Chest · Shoulders · Triceps',
    category: 'hypertrophy',
    rank: 'B',
    duration: 75,
    description: 'Monday gym session. Incline press focus with shoulder and tricep volume. Ends with incline walk.',
    exercises: [
      { name: 'Incline Dumbbell Press', sets: 4, reps: 7, unit: 'reps', rest: 150, type: 'strength', notes: '6–8 reps · lead set' },
      { name: 'Chest Press Machine', sets: 3, reps: 9, unit: 'reps', rest: 90, type: 'strength', notes: '8–10 reps' },
      { name: 'Low-to-High Cable Fly', sets: 3, reps: 13, unit: 'reps', rest: 60, type: 'strength', notes: '12–15 reps' },
      { name: 'Pec Deck', sets: 3, reps: 13, unit: 'reps', rest: 60, type: 'strength', notes: '12–15 reps' },
      { name: 'Seated DB Shoulder Press', sets: 3, reps: 9, unit: 'reps', rest: 90, type: 'strength', notes: '8–10 reps' },
      { name: 'Dumbbell Lateral Raises', sets: 4, reps: 13, unit: 'reps', rest: 60, type: 'strength', notes: '12–15 reps' },
      { name: 'Overhead Cable Extensions', sets: 3, reps: 11, unit: 'reps', rest: 60, type: 'strength', notes: '10–12 reps' },
      { name: 'Tricep Pushdowns', sets: 3, reps: 11, unit: 'reps', rest: 60, type: 'strength', notes: '10–12 reps' },
      { name: 'Incline Walk', sets: 1, reps: 20, unit: 'minutes', rest: 0, type: 'cardio', notes: '12% grade · 5–5.5 km/h' },
    ],
  },
  {
    id: 'hw2',
    name: 'HIIT + Pump — Home',
    category: 'hypertrophy',
    rank: 'B',
    duration: 60,
    description: 'Tuesday home session. Jump rope HIIT followed by push, shoulder, core, and forearm work.',
    exercises: [
      { name: 'Jump Rope HIIT', sets: 1, reps: 20, unit: 'minutes', rest: 0, type: 'cardio', notes: '5 min easy · 8×40s on/20s rest · 3 min cool-down' },
      { name: 'Decline Push-ups', sets: 3, reps: 10, unit: 'reps', rest: 60, type: 'strength', notes: 'AMRAP · feet on chair' },
      { name: 'Deficit Push-ups', sets: 3, reps: 10, unit: 'reps', rest: 60, type: 'strength', notes: '8–12 reps · hands on DBs' },
      { name: 'Pike Push-ups', sets: 3, reps: 11, unit: 'reps', rest: 60, type: 'strength', notes: '10–12 reps' },
      { name: 'Band Lateral Raises', sets: 3, reps: 17, unit: 'reps', rest: 60, type: 'strength', notes: '15–20 reps' },
      { name: 'Band Pull-Aparts', sets: 3, reps: 17, unit: 'reps', rest: 60, type: 'strength', notes: '15–20 reps' },
      { name: 'Hanging Leg Raises', sets: 3, reps: 10, unit: 'reps', rest: 60, type: 'endurance', notes: 'Max reps · pull-up bar' },
      { name: 'Reverse Crunches', sets: 3, reps: 13, unit: 'reps', rest: 60, type: 'endurance', notes: '12–15 reps' },
      { name: 'Ab Rollout', sets: 3, reps: 9, unit: 'reps', rest: 60, type: 'endurance', notes: '8–10 reps' },
      { name: 'Plank Hold', sets: 2, reps: 45, unit: 'seconds', rest: 60, type: 'endurance' },
      { name: 'Dead Hang', sets: 3, reps: 30, unit: 'seconds', rest: 60, type: 'endurance', notes: 'Max hold · forearm finisher' },
    ],
  },
  {
    id: 'hw3',
    name: 'Pull A — Lats · Rear Delt · Biceps',
    category: 'hypertrophy',
    rank: 'B',
    duration: 80,
    description: 'Wednesday gym session. High-volume lat work with rear delt, bicep, and core finisher.',
    exercises: [
      { name: 'Wide Pulldowns', sets: 5, reps: 9, unit: 'reps', rest: 120, type: 'strength', notes: '8–10 reps · lead set' },
      { name: 'Narrow Pulldowns', sets: 3, reps: 11, unit: 'reps', rest: 90, type: 'strength', notes: '10–12 reps' },
      { name: 'Seated Cable Row', sets: 3, reps: 11, unit: 'reps', rest: 90, type: 'strength', notes: '10–12 reps' },
      { name: 'Rear Delt Fly (Pec Deck)', sets: 4, reps: 13, unit: 'reps', rest: 60, type: 'strength', notes: '12–15 reps' },
      { name: 'Cable Face Pulls', sets: 3, reps: 17, unit: 'reps', rest: 60, type: 'strength', notes: '15–20 reps' },
      { name: 'Preacher Curls', sets: 3, reps: 11, unit: 'reps', rest: 90, type: 'strength', notes: '10–12 reps' },
      { name: 'Incline Dumbbell Curls', sets: 3, reps: 11, unit: 'reps', rest: 90, type: 'strength', notes: '10–12 reps' },
      { name: 'Hammer Curls', sets: 2, reps: 11, unit: 'reps', rest: 60, type: 'strength', notes: '10–12 reps' },
      { name: 'Hanging Leg Raises', sets: 4, reps: 12, unit: 'reps', rest: 60, type: 'endurance', notes: '10–15 reps' },
      { name: 'Machine Crunches', sets: 3, reps: 13, unit: 'reps', rest: 60, type: 'endurance', notes: '12–15 reps' },
      { name: 'Reverse Crunches', sets: 3, reps: 13, unit: 'reps', rest: 60, type: 'endurance', notes: '12–15 reps' },
      { name: 'Stationary Bike', sets: 1, reps: 20, unit: 'minutes', rest: 0, type: 'cardio', notes: 'Moderate pace' },
    ],
  },
  {
    id: 'hw4',
    name: 'Legs A — Quads · Hamstrings · Calves',
    category: 'hypertrophy',
    rank: 'B',
    duration: 55,
    description: 'Thursday gym session. Bulgarian split squat (upright) focus with leg extensions and calves.',
    exercises: [
      { name: 'Bulgarian Split Squats', sets: 4, reps: 9, unit: 'reps', rest: 120, type: 'strength', notes: '8–10 per side · torso upright' },
      { name: 'Leg Extensions', sets: 4, reps: 11, unit: 'reps', rest: 90, type: 'strength', notes: '10–12 reps' },
      { name: 'Leg Curls', sets: 3, reps: 11, unit: 'reps', rest: 90, type: 'strength', notes: '10–12 reps' },
      { name: 'Calf Raises (Leg Press)', sets: 4, reps: 17, unit: 'reps', rest: 60, type: 'strength', notes: '15–20 reps' },
      { name: 'Lower Back Extensions', sets: 3, reps: 13, unit: 'reps', rest: 60, type: 'strength', notes: '12–15 reps' },
      { name: 'Dumbbell Lateral Raises', sets: 3, reps: 13, unit: 'reps', rest: 60, type: 'strength', notes: '12–15 reps · shoulder accessory' },
    ],
  },
  {
    id: 'hw5',
    name: 'Push B — Chest · Shoulders · Triceps',
    category: 'hypertrophy',
    rank: 'B',
    duration: 70,
    description: 'Friday gym session. Cable lateral focus with higher pec deck volume. Ends with jump rope HIIT.',
    exercises: [
      { name: 'Incline Dumbbell Press', sets: 3, reps: 9, unit: 'reps', rest: 120, type: 'strength', notes: '8–10 reps' },
      { name: 'Chest Press Machine', sets: 3, reps: 9, unit: 'reps', rest: 90, type: 'strength', notes: '8–10 reps' },
      { name: 'Pec Deck', sets: 4, reps: 11, unit: 'reps', rest: 60, type: 'strength', notes: '10–12 reps' },
      { name: 'Cable Lateral Raises', sets: 5, reps: 13, unit: 'reps', rest: 60, type: 'strength', notes: '12–15 reps' },
      { name: 'Seated DB Shoulder Press', sets: 3, reps: 9, unit: 'reps', rest: 90, type: 'strength', notes: '8–10 reps' },
      { name: 'One Arm Cable Kickbacks', sets: 3, reps: 13, unit: 'reps', rest: 60, type: 'strength', notes: '12–15 reps per arm' },
      { name: 'Tricep Pushdowns', sets: 3, reps: 11, unit: 'reps', rest: 60, type: 'strength', notes: '10–12 reps' },
      { name: 'Hanging Leg Raises', sets: 3, reps: 12, unit: 'reps', rest: 60, type: 'endurance', notes: '10–15 reps' },
      { name: 'Ab Rollout', sets: 3, reps: 10, unit: 'reps', rest: 60, type: 'endurance', notes: '8–12 reps' },
      { name: 'Jump Rope HIIT', sets: 1, reps: 15, unit: 'minutes', rest: 0, type: 'cardio', notes: '2 min easy · 6×30s on/30s rest · 3 min cool-down' },
    ],
  },
  {
    id: 'hw6',
    name: 'Pull B — Lats · Traps · Biceps · Forearms',
    category: 'hypertrophy',
    rank: 'B',
    duration: 70,
    description: 'Saturday gym session. Trap and rear delt accessory added. Ends with incline walk.',
    exercises: [
      { name: 'Wide Pulldowns', sets: 4, reps: 9, unit: 'reps', rest: 120, type: 'strength', notes: '8–10 reps' },
      { name: 'Seated Cable Row', sets: 4, reps: 11, unit: 'reps', rest: 90, type: 'strength', notes: '10–12 reps' },
      { name: 'Wide Rows', sets: 2, reps: 13, unit: 'reps', rest: 60, type: 'strength', notes: '12–15 reps · trap focus' },
      { name: 'Rear Delt Fly (Pec Deck)', sets: 4, reps: 13, unit: 'reps', rest: 60, type: 'strength', notes: '12–15 reps' },
      { name: 'Cable Face Pulls', sets: 3, reps: 17, unit: 'reps', rest: 60, type: 'strength', notes: '15–20 reps' },
      { name: 'Reverse EZ Bar Curls', sets: 3, reps: 11, unit: 'reps', rest: 90, type: 'strength', notes: '10–12 reps' },
      { name: 'Hammer Curls', sets: 3, reps: 11, unit: 'reps', rest: 60, type: 'strength', notes: '10–12 reps' },
      { name: 'Cable Wrist Curls', sets: 3, reps: 13, unit: 'reps', rest: 60, type: 'strength', notes: '12–15 reps · forearm finisher' },
      { name: 'Machine Crunches', sets: 3, reps: 13, unit: 'reps', rest: 60, type: 'endurance', notes: '12–15 reps' },
      { name: 'Incline Walk', sets: 1, reps: 20, unit: 'minutes', rest: 0, type: 'cardio', notes: '12% grade · 5–5.5 km/h' },
    ],
  },
  {
    id: 'hw7',
    name: 'Legs B — Hamstrings · Quads · Calves',
    category: 'hypertrophy',
    rank: 'B',
    duration: 55,
    description: 'Sunday gym session. Hamstring-biased split squat with quad and calf work.',
    exercises: [
      { name: 'Bulgarian Split Squats', sets: 4, reps: 11, unit: 'reps', rest: 120, type: 'strength', notes: '10–12 per side · torso 10–15° forward' },
      { name: 'Leg Curls', sets: 4, reps: 11, unit: 'reps', rest: 90, type: 'strength', notes: '10–12 reps' },
      { name: 'Leg Extensions', sets: 3, reps: 11, unit: 'reps', rest: 90, type: 'strength', notes: '10–12 reps' },
      { name: 'Calf Raises (Leg Press)', sets: 4, reps: 17, unit: 'reps', rest: 60, type: 'strength', notes: '15–20 reps' },
      { name: 'Lower Back Extensions', sets: 3, reps: 13, unit: 'reps', rest: 60, type: 'strength', notes: '12–15 reps' },
      { name: 'Cable Lateral Raises', sets: 3, reps: 13, unit: 'reps', rest: 60, type: 'strength', notes: '12–15 reps · shoulder accessory' },
    ],
  },
];

// Boss Battle configurations
export const BOSS_BATTLES = [
  {
    id: 'boss1',
    name: 'Ant King\'s Gauntlet',
    description: 'Face the wrath of the Ant King. 500 reps stand between you and victory.',
    difficulty: 'S',
    xpReward: 500,
    titleReward: 'Ant Slayer',
    timeLimit: 3600,
    exercises: [
      { name: 'Push-ups', totalReps: 150, type: 'strength' },
      { name: 'Squats', totalReps: 150, type: 'strength' },
      { name: 'Burpees', totalReps: 100, type: 'cardio' },
      { name: 'Sit-ups', totalReps: 100, type: 'endurance' },
    ],
    bossHP: 500,
    lore: 'The Ant King descended upon you with overwhelming force. Only 500 reps can drive it back into the shadows.',
  },
  {
    id: 'boss2',
    name: 'Demon Castle Siege',
    description: 'Storm the Demon Castle. Every rep shatters another gate.',
    difficulty: 'A',
    xpReward: 400,
    titleReward: 'Castle Breaker',
    timeLimit: 2700,
    exercises: [
      { name: 'Pull-ups', totalReps: 80, type: 'strength' },
      { name: 'Dips', totalReps: 100, type: 'strength' },
      { name: 'Jump Squats', totalReps: 80, type: 'cardio' },
      { name: 'Plank', totalReps: 300, type: 'endurance', unit: 'seconds' },
    ],
    bossHP: 560,
    lore: 'The Demon Castle looms before you. Its gates will not yield to the weak.',
  },
  {
    id: 'boss3',
    name: 'Shadow Soldier Trial',
    description: 'Prove your worth to command shadow soldiers. A foundational test.',
    difficulty: 'C',
    xpReward: 300,
    titleReward: 'Shadow Commander',
    timeLimit: 2400,
    exercises: [
      { name: 'Push-ups', totalReps: 100, type: 'strength' },
      { name: 'Squats', totalReps: 100, type: 'strength' },
      { name: 'Sit-ups', totalReps: 100, type: 'endurance' },
    ],
    bossHP: 300,
    lore: 'The shadow soldiers await a worthy commander. Prove yourself worthy of their loyalty.',
  },
  {
    id: 'boss4',
    name: 'Ice Elf Queen\'s Fury',
    description: 'Withstand the Ice Elf Queen\'s relentless assault. Speed is your only salvation.',
    difficulty: 'S',
    xpReward: 600,
    titleReward: 'Frost Conqueror',
    timeLimit: 3000,
    exercises: [
      { name: 'High Knees', totalReps: 200, type: 'cardio' },
      { name: 'Burpees', totalReps: 150, type: 'cardio' },
      { name: 'Mountain Climbers', totalReps: 150, type: 'cardio' },
      { name: 'Jump Squats', totalReps: 100, type: 'strength' },
    ],
    bossHP: 600,
    lore: 'The Ice Elf Queen moves with devastating speed. Match her pace or be consumed by frost.',
  },
];

// Motivational quotes from Sung Jin-Woo
export const JINWOO_QUOTES = [
  '"I alone am the exception."',
  '"The strong prey on the weak. That is the law of nature."',
  '"Getting stronger is the only option."',
  '"Rise. And prove your worth to the System."',
  '"Even if no one else acknowledges it, I will keep moving forward."',
  '"The day I stop growing is the day I die."',
  '"Fear is for those who have something to lose. I have only goals."',
  '"Shadows never retreat."',
  '"Power is everything. Earn it."',
  '"The System rewards those who do not falter."',
];

export function getRandomQuote() {
  return JINWOO_QUOTES[Math.floor(Math.random() * JINWOO_QUOTES.length)];
}

export function getWeeklyBoss() {
  const week = Math.floor(Date.now() / (7 * 24 * 60 * 60 * 1000));
  return BOSS_BATTLES[week % BOSS_BATTLES.length];
}

export const CATEGORY_LABELS = {
  strength: 'Strength',
  cardio: 'Cardio',
  endurance: 'Endurance',
  flexibility: 'Flexibility',
  hypertrophy: 'Hypertrophy',
};
